language: objective-c

before_install:
    - brew update
    - brew uninstall xctool && brew install xctool --HEAD

script: xctool -project InputValidatorsExample/InputValidatorsExample.xcodeproj -scheme InputValidatorsExample
