language: objective-c

before_install:
    - brew update
    - brew uninstall xctool && brew install xctool

script: xctool -project InputValidatorsExample/InputValidatorsExample.xcodeproj -scheme InputValidatorsExample -sdk iphonesimulator  ARCHS="armv7 armv7s i386" test
